# config.yaml

project_name: "AI README Improver"
email: "hamzahabib10@gmail.com"
logo_path: "assets/logo.png"

badges:
  - name: "Build Status"
    image_url: "https://img.shields.io/github/actions/workflow/status/habib13352/ai-readme-improver/readme-improver.yml?branch=main"
    link: "https://github.com/habib13352/ai-readme-improver/actions"
  - name: "License"
    image_url: "https://img.shields.io/badge/license-MIT-blue.svg"
    link: "LICENSE"

# Now we drive each major section via its own prompt file:
sections:
  - name: "Table of Contents"
    enabled: true
    prompt_file: "prompts/toc.prompt"

  - name: "Demo"
    enabled: true
    prompt_file: "prompts/demo.prompt"

  - name: "Installation"
    enabled: true
    prompt_file: "prompts/installation.prompt"

  - name: "Usage"
    enabled: true
    prompt_file: "prompts/usage.prompt"

  - name: "Features"
    enabled: true
    prompt_file: "prompts/features.prompt"

  - name: "Configuration"
    enabled: true
    prompt_file: "prompts/configuration.prompt"

  - name: "Contributing"
    enabled: true
    prompt_file: "prompts/contributing.prompt"

  - name: "License"
    enabled: true
    prompt_file: "prompts/license.prompt"

  - name: "Maintainers"
    enabled: true
    prompt_file: "prompts/maintainers.prompt"

  - name: "Acknowledgements"
    enabled: true
    prompt_file: "prompts/acknowledgements.prompt"

  - name: "Contact"
    enabled: true
    prompt_file: "prompts/contact.prompt"
