project_name: "AI README Improver"
email: "hamzahabib10@gmail.com"
logo_path: "assets/logo.png"
badges:
  - name: "Build Status"
    image_url: "https://img.shields.io/github/actions/workflow/status/username/repo/ci.yml"
    link: "https://github.com/habib13352/ai-readme-improver/actions"
extra_sections:
  - title: "Maintainers"
    content: |
      - Hamza Habib (@habib13352)
  - title: "Acknowledgements"
    content: |
      Thanks to OpenAI and the community for feedback.
sections:
  - name: Badges
    prompt_file: prompts/update_badges.prompt
    enabled: true
  - name: Installation
    prompt_file: prompts/update_installation.prompt
    enabled: true
  - name: Usage
    prompt_file: prompts/update_usage.prompt
    enabled: true
  - name: Changelog
    prompt_file: prompts/update_changelog.prompt
    enabled: true
  - name: API Reference
    prompt_file: prompts/generate_api_reference.prompt
    enabled: true
