project_name: "AI README Improver"
email: "hamzahabib10@gmail.com"
logo_path: "assets/logo.png"
badges:
  - name: "Build Status"
    image_url: "https://img.shields.io/github/actions/workflow/status/username/repo/ci.yml"
    link: "https://github.com/username/repo/actions"
extra_sections:
  - title: "Maintainers"
    content: |
      - Hamza Habib (@habib13352)
  - title: "Acknowledgements"
    content: |
      Thanks to OpenAI and the community for feedback.
