name: Auto Docs
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: markdownlint README.md docs/**/*.md
      - run: linkchecker README.md
      - run: python scripts/update_readme.py
      - name: Commit docs
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md docs/
          git diff --cached --quiet || git commit -m 'docs: auto update'
          git push origin HEAD:docs/auto-update
