name: "AI README Auto Update"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install "openai>=1.0" python-dotenv markdown2

      - name: Load secrets into env
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      - name: Run AI README Improver
        run: python main.py

      - name: Archive old README and replace
        run: |
          mkdir -p readme-archive
          timestamp=$(date +'%Y%m%d_%H%M%S')
          cp README.md "readme-archive/README.$timestamp.md"
          cp README.improved.md README.md

      - name: Commit and push updated README
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: auto update README"
          file_pattern: "README.md readme-archive/*"
